#!/usr/bin/env python3
import os
import sys
import json
import subprocess
from PyQt6.QtWidgets import QApplication, QMessageBox

EXTENSION_UUID = "linux-note-app-integration@stup"
APP_WM_CLASS = "gnome_linux_note_app"

EXTENSION_METADATA = {
    "name": "Linux Note App Integration",
    "description": "Companion extension for the Linux Note App. Automatically generated by the app to hide it from Alt-Tab.",
    "uuid": EXTENSION_UUID,
    "shell-version": ["45", "46", "47", "48"]
}

EXTENSION_JS_CODE = """
import GLib from 'gi://GLib';
import * as altTab from 'resource:///org/gnome/shell/ui/altTab.js';
import { Extension, InjectionManager } from 'resource:///org/gnome/shell/extensions/extension.js';

export default class NoteAppIntegrationExtension extends Extension {
    constructor(metadata) {
        super(metadata);
        this._injectionManager = null;
        this._windowCreatedId = null;
    }

    enable() {
        this._injectionManager = new InjectionManager();

        // Hide any note window — those whose title starts with '[Note]'
        // The Main Window title is 'Sticky Notes' — no [Note] prefix — stays visible.
        const isNoteWindow = (window) => {
            if (!window) return false;
            const title = window.get_title();
            return title !== null && title.startsWith('[Note]');
        };

        // Hide from Alt-Tab window switcher
        this._injectionManager.overrideMethod(
            altTab.WindowSwitcherPopup.prototype,
            '_getWindowList',
            (originalMethod) => {
                return function (...args) {
                    const windows = originalMethod.call(this, ...args);
                    return windows.filter(window => !isNoteWindow(window));
                };
            }
        );

        // Hide from Super+` (window cycler within same app)
        this._injectionManager.overrideMethod(
            altTab.WindowCyclerPopup.prototype,
            '_getWindows',
            (originalMethod) => {
                return function (...args) {
                    const windows = originalMethod.call(this, ...args);
                    return windows.filter(window => !isNoteWindow(window));
                };
            }
        );

        // Hide from group cycler if available
        if (altTab.GroupCyclerPopup) {
            this._injectionManager.overrideMethod(
                altTab.GroupCyclerPopup.prototype,
                '_getWindows',
                (originalMethod) => {
                    return function (...args) {
                        const windows = originalMethod.call(this, ...args);
                        return windows.filter(window => !isNoteWindow(window));
                    };
                }
            );
        }

        // Hide from App Switcher (Alt-Tab default): only remove the app entry
        // if ALL its windows are notes (i.e. the main window is not open)
        this._injectionManager.overrideMethod(
            altTab.AppSwitcherPopup.prototype,
            '_init',
            (originalMethod) => {
                return function (...args) {
                    originalMethod.call(this, ...args);
                    if (this._items && this._items.length > 0) {
                        const indicesToRemove = [];
                        for (let i = 0; i < this._items.length; i++) {
                            const appIcon = this._items[i];
                            if (appIcon && appIcon.app) {
                                const windows = appIcon.app.get_windows();
                                const visibleWindows = windows.filter(w => !isNoteWindow(w));
                                if (visibleWindows.length === 0) {
                                    indicesToRemove.push(i);
                                }
                            }
                        }
                        for (let i = indicesToRemove.length - 1; i >= 0; i--) {
                            const idx = indicesToRemove[i];
                            if (this._switcherList && typeof this._switcherList.removeItem === 'function') {
                                this._switcherList.icons.splice(idx, 1);
                                this._switcherList.removeItem(idx);
                            }
                        }
                        this._items = this._switcherList ? this._switcherList.icons : [];
                    }
                };
            }
        );

        // Make Emergency notes sticky across all workspaces and always on top of all windows
        const setupNoteWindow = (window) => {
            if (!window) return;
            const applyWindowRules = () => {
                const title = window.get_title();
                const wmClass = window.get_wm_class();
                
                const isNote = (title && title.startsWith('[Note]'));
                const isEmergency = isNote && title.startsWith('[Note] Emergency');

                if (isNote) {
                    try {
                        window.stick(); // Pin across all workspaces
                        console.log(`[LinuxNoteExtension] Applied stick() to: ${title}`);
                    } catch (e) {
                        console.error(`[LinuxNoteExtension] Error sticking window: ${e}`);
                    }

                    if (isEmergency) {
                        try {
                            window.make_above(); // Keep always on top
                            console.log(`[LinuxNoteExtension] Applied make_above() to: ${title}`);
                        } catch (e) {
                            console.error(`[LinuxNoteExtension] Error making window above: ${e}`);
                        }
                    }
                }
            };

            applyWindowRules();

            // Run on multiple intervals to catch Wayland title propagation
            [50, 150, 300, 600, 1200, 2500].forEach(delay => {
                GLib.timeout_add(GLib.PRIORITY_DEFAULT, delay, () => {
                    applyWindowRules();
                    return GLib.SOURCE_REMOVE;
                });
            });

            try {
                window.connect('notify::title', applyWindowRules);
                window.connect('notify::above', applyWindowRules);
            } catch (e) {}
        };

        this._windowCreatedId = global.display.connect('window-created', (_display, window) => {
            setupNoteWindow(window);
        });

        // Set up any already-open note windows
        const workspaceManager = global.display.get_workspace_manager();
        for (let i = 0; i < workspaceManager.n_workspaces; i++) {
            const workspace = workspaceManager.get_workspace_by_index(i);
            workspace.list_windows().forEach(w => setupNoteWindow(w));
        }
    }

    disable() {
        if (this._injectionManager) {
            this._injectionManager.clear();
            this._injectionManager = null;
        }
        if (this._windowCreatedId) {
            global.display.disconnect(this._windowCreatedId);
            this._windowCreatedId = null;
        }
    }
}
"""


def is_extension_installed():
    home = os.path.expanduser("~")
    ext_dir = os.path.join(home, ".local", "share", "gnome-shell", "extensions", EXTENSION_UUID)
    return os.path.exists(os.path.join(ext_dir, "metadata.json"))


def install_and_enable_extension(parent_widget=None):
    home = os.path.expanduser("~")
    ext_dir = os.path.join(home, ".local", "share", "gnome-shell", "extensions", EXTENSION_UUID)

    # 1. Check if already installed
    if is_extension_installed():
        print("Extension is already installed.")
        return

    # 2. Ask user for permission
    reply = QMessageBox.question(
        parent_widget,
        "Install Integration Extension?",
        "To hide this app from the Alt-Tab switcher seamlessly, we need to install a lightweight companion GNOME Extension.\n\nDo you want to install it now?",
        QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
        QMessageBox.StandardButton.Yes
    )

    if reply != QMessageBox.StandardButton.Yes:
        print("User cancelled installation.")
        return

    # 3. Create extension files
    os.makedirs(ext_dir, exist_ok=True)
    with open(os.path.join(ext_dir, "metadata.json"), "w") as f:
        json.dump(EXTENSION_METADATA, f, indent=4)

    with open(os.path.join(ext_dir, "extension.js"), "w") as f:
        f.write(EXTENSION_JS_CODE)

    # 4. Attempt to enable
    try:
        subprocess.run(["gnome-extensions", "enable", EXTENSION_UUID], capture_output=True, text=True)
    except FileNotFoundError:
        pass

    # 5. Notify user to log out
    QMessageBox.information(
        parent_widget,
        "Installation Complete",
        "The extension has been installed!\n\nSince this is a new extension, GNOME requires you to log out and log back in for it to be recognized. After logging back in, this app will automatically be hidden from the Alt-Tab switcher."
    )


if __name__ == "__main__":
    app = QApplication(sys.argv)
    install_and_enable_extension()
